### ISSUE TITLE
Error while running `prisma2 lift up` in a new directory

### ISSUE THREAD

**Issue by matthewmueller** [prisma/next#13]
I started fresh in a new directory (not `prisma/next`):

**Steps to Reproduce**

```
mkdir prisma-2 && cd prisma-2
yarn add @prisma/prototype
touch datamodel.prisma
```

Inside `datamodel.prisma`, I added:

```
model User {
  id Int @id
  first_name String
}
```

Next I ran:

```sh
./node_modules/.bin/prisma2 lift up
```

**Resulting in**

```
Error: Error in lift engine for rpc listMigrations: [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:33] m.make::<barrel::backend::Sqlite>() = "CREATE TABLE IF NOT EXISTS \"migration_engine\".\"_Migration\" (\"revision\" INTEGER NOT NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError(SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database: /Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/db/migration_engine.db"))

stack backtrace:
   0: backtrace::backtrace::trace::h862903ac52cf58ce (0x1019bf8fe)
   1: backtrace::capture::Backtrace::new_unresolved::hb838890310508129 (0x1019beac8)
   2: failure::backtrace::internal::InternalBacktrace::new::he7020c6c20003af5 (0x1019be469)
   3: <failure::backtrace::Backtrace as core::default::Default>::default::hbdcce0dc805803fe (0x1019be655)
   4: prisma_query::connector::sqlite::<impl core::convert::From<rusqlite::error::Error> for prisma_query::error::Error>::from::h79eaa967bb9b5129 (0x101783126)
   5: prisma_query::connector::sqlite::Sqlite::attach_database::h32308026c6c86b4b (0x10176d54b)
   6: <prisma_query::connector::sqlite::Sqlite as prisma_query::transaction::Connectional>::with_connection::h3cffc4af6dba39da (0x1016d2116)
   7: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence<C>>::init::he908b845b7ceac5b (0x1016e1d8c)
   8: <F as jsonrpc_core::calls::RpcMethodSimple>::call::h3a45d41c640566c9 (0x1016a13fc)
   9: <F as jsonrpc_core::calls::RpcMethod<T>>::call::h1248daccfde1c695 (0x10165af4c)
  10: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h3d1b435ca4e95c94 (0x101661932)
  11: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll::hc1de95f3c2a0e42b (0x101654240)
  12: <futures::future::map::Map<A, F> as futures::future::Future>::poll::hadd77e65c7fd1f79 (0x101667a9f)
  13: <futures::future::either::Either<A, B> as futures::future::Future>::poll::h01c922ccc6fa78dc (0x101661bc0)
  14: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::he06fc87daaa8e64e (0x1016a54e1)
  15: futures::future::Future::wait::h67e3c6888e051b25 (0x1016678fa)
  16: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync::hfa6a2f10b2714dff (0x101658cbf)
  17: migration_core::rpc_api::RpcApi::handle::h176bad87cf66f5e8 (0x1016a688b)
  18: migration_engine::main::h59aad957f6ba49cc (0x10162780d)
  19: std::rt::lang_start::{{closure}}::h52a1cb7acf5ab7bd (0x1016277b6)
  20: std::panicking::try::do_call::h20c95c457c762d5f (0x1019d4808)
  21: ___rust_maybe_catch_panic (0x1019d782f)
  22: std::rt::lang_start_internal::he82d111f45e8971a (0x1019d522e)
  23: _main (0x101627869))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <sql_migration_connector::sql_migration_persistence::SqlMigrationPersistence<C>>::init
  10: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  11: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  12: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  13: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  14: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  15: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  16: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future
  17: futures::future::Future::wait
  18: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
  19: migration_core::rpc_api::RpcApi::handle
  20: migration_engine::main
  21: std::rt::lang_start::{{closure}}
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
  24: std::rt::lang_start_internal
  25: main

    at ChildProcess.<anonymous> (/Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/node_modules/@prisma/prototype/build/index.js:290897:28)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
```

**Comment by matthewmueller** [comment]
**Steps to Fix:**

1. Manually create `db` directory
2. Run `./node_modules/.bin/prisma2 lift create`
3. Run `./node_modules/.bin/prisma2 lift up`
