### ISSUE TITLE
`prisma generate` shouldn't require a prisma.yml

### ISSUE THREAD

**Issue by matthewmueller** [prisma/next#16]
**Steps to Reproduce**

Run `./node_modules/.bin/prisma2 generate` on a fresh project:

```
Error: Could not find prisma.yml
    at PhotonGenerate.<anonymous> (/Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/node_modules/@prisma/prototype/build/index.js:88840:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/node_modules/@prisma/prototype/build/index.js:88770:58)
```

**Current State**

`datamodel.prisma`:

```
model User {
  id Int @id
  first_name String
}
```

File structure:

```
.
├── datamodel.prisma
├── db
│   └── migration_engine.db
├── migrations
│   ├── 20190610130032-setup
│   │   ├── README.md
│   │   ├── datamodel.prisma
│   │   └── steps.json
│   └── lift.lock
├── package.json
└── yarn.lock
```

**Comment by matthewmueller** [comment]
**Steps to Fix**

```
touch prisma.yml
```

In my `prisma.yml`:

```
datamodel: datamodel.prisma
```
