### ISSUE TITLE
Photon shouldn't require `prisma.yml` "databases" field

### ISSUE THREAD

**Issue by matthewmueller** [prisma/next#17]
**Steps to Reproduce**

```
./node_modules/.bin/prisma2 generate
touch index.js
```

Inside `index.js`

```js
const { Photon } = require('@generated/photon')
const client = new Photon({})
```

Then run:

```
node index.js
```

**Resulting in**

```
Engine path: /Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/node_modules/@generated/photon/runtime/prisma
/Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/node_modules/@generated/photon/runtime/index.js:1175
                    throw new Engine_1.PhotonError(`Error in query engine: ` + this.errorLogs, undefined, undefined, this.errorLogs);
                    ^

Error: Error in query engine: thread 'main' panicked at 'Unable to parse YML config.: Message("missing field `databases`", Some(Pos { marker: Marker { index: 4, line: 1, col: 4 }, path: "." }))', src/libcore/result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

    at ChildProcess.<anonymous> (/Users/m/Code/src/github.com/matthewmueller/prisma/prisma-2/node_modules/@generated/photon/runtime/index.js:1175:27)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
```

**Current State**

`datamodel.prisma`

```
model User {
  id Int @id
  first_name String
}
```

`prisma.yml`

```
datamodel: datamodel.prisma
```

File structure:

```
.
├── datamodel.prisma
├── db
│   └── migration_engine.db
├── index.js
├── migrations
│   ├── 20190610130032-setup
│   │   ├── README.md
│   │   ├── datamodel.prisma
│   │   └── steps.json
│   └── lift.lock
├── package.json
├── prisma.yml
└── yarn.lock

3 directories, 10 files
```

**Comment by matthewmueller** [comment]
**Workaround**

Add databases object in `prisma.yml`

```
datamodel: datamodel.prisma
databases:
  default:
    connector: sqlite-native
    databaseFile: ./db/migration_engine.db
    migrations: true
    active: true
    rawAccess: true
```

Then run:

```js
./node_modules/.bin/prisma2 generate
node index.js # it works
```

This one took me some time to figure out... I guess we're hardcoding `prisma.yml` during generation?
