### ISSUE TITLE
Initial migration fails with medium-complex datamodel

### ISSUE THREAD

**Issue by nikolasburk** [prisma/next#23]
I want to get started with a new Prisma project but my initial setup fails. I'm trying to create a new migration to map this datamodel to the DB:

```
model User {
  id: Int @id
  createdAt: DateTime @default(now())
  email: String @unique
  name: String
  role: Role @default(value: USER)
  posts: Post[]
  profile: Profile @relation(link: INLINE)
}

model Profile {
  id: Int @id
  user: User
  bio: String
}

model Post {
  id: Int @id
  createdAt: DateTime @default(now())
  updatedAt: DateTime @updatedAt
  author: User
  published: Boolean @default(value: false)
  categories: Category[] @relation(link: TABLE, name: "PostToCategory")
}

model Category {
  id: Int @id
  name: String
  posts: Post[] @relation(name: "PostToCategory")
}

model PostToCategory {
  post: Post
  category: Category
}

enum Role {
  USER
  ADMIN
}
```

When running `prisma2 lift create --name 'init'`, I get the following error:

```
$ prisma2 lift create
✔ Name of migration … init
Error: Error in lift engine for rpc inferMigrationSteps:
  [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:33] m.make::<barrel::backend::Sqlite>() = "CREATE TABLE IF NOT EXISTS \"migration_engine\".\"_Migration\" (\"revision\" INTEGER NOT NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
[/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/8ea8214/src/connector/sqlite.rs:70] visitor::Sqlite::build(q) = (
    "SELECT `_Migration`.* FROM `_Migration` WHERE `status` = ? ORDER BY `revision` DESC",
    [
        Text(
            "Success"
        )
    ]
)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::fold
  10: sql_migration_connector::database_schema_calculator::DatabaseSchemaCalculator::calculate
  11: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::database_migration_inferrer::DatabaseMigrationInferrer<sql_migration_connector::sql_migration::SqlMigration>>::infer
  12: <migration_core::commands::infer_migration_steps::InferMigrationStepsCommand as migration_core::commands::command::MigrationCommand>::execute
  13: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  14: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  15: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  16: <futures::future::chain::Chain<A, B, C>>::poll
  17: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  20: futures::task_impl::std::set
  21: <std::thread::local::LocalKey<T>>::with
  22: futures::future::Future::wait
  23: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
  24: migration_core::rpc_api::RpcApi::handle
  25: migration_engine::main
  26: std::rt::lang_start::{{closure}}
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
  29: std::rt::lang_start_internal
  30: main

    at ChildProcess.<anonymous> (/Users/nikolasburk/.config/yarn/global/node_modules/prisma2/build/index.js:82645:28)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
~/D/demo-project $ prisma2 lift create --name 'init'
Error: Error in lift engine for rpc inferMigrationSteps:
  [migration-engine/connectors/sql-migration-connector/src/sql_migration_persistence.rs:33] m.make::<barrel::backend::Sqlite>() = "CREATE TABLE IF NOT EXISTS \"migration_engine\".\"_Migration\" (\"revision\" INTEGER NOT NULL PRIMARY KEY, \"name\" TEXT NOT NULL, \"datamodel\" TEXT NOT NULL, \"status\" TEXT NOT NULL, \"applied\" INTEGER NOT NULL, \"rolled_back\" INTEGER NOT NULL, \"datamodel_steps\" TEXT NOT NULL, \"database_migration\" TEXT NOT NULL, \"errors\" TEXT NOT NULL, \"started_at\" DATE NOT NULL, \"finished_at\" DATE);"
[/var/root/.cargo/git/checkouts/prisma-query-a8c45647247f5d6d/8ea8214/src/connector/sqlite.rs:70] visitor::Sqlite::build(q) = (
    "SELECT `_Migration`.* FROM `_Migration` WHERE `status` = ? ORDER BY `revision` DESC",
    [
        Text(
            "Success"
        )
    ]
)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::panicking::panic
   9: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::fold
  10: sql_migration_connector::database_schema_calculator::DatabaseSchemaCalculator::calculate
  11: <sql_migration_connector::sql_database_migration_inferrer::SqlDatabaseMigrationInferrer as migration_connector::database_migration_inferrer::DatabaseMigrationInferrer<sql_migration_connector::sql_migration::SqlMigration>>::infer
  12: <migration_core::commands::infer_migration_steps::InferMigrationStepsCommand as migration_core::commands::command::MigrationCommand>::execute
  13: <F as jsonrpc_core::calls::RpcMethodSimple>::call
  14: <F as jsonrpc_core::calls::RpcMethod<T>>::call
  15: <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll
  16: <futures::future::chain::Chain<A, B, C>>::poll
  17: <futures::future::then::Then<A, B, F> as futures::future::Future>::poll
  18: <futures::future::map::Map<A, F> as futures::future::Future>::poll
  19: <futures::future::either::Either<A, B> as futures::future::Future>::poll
  20: futures::task_impl::std::set
  21: <std::thread::local::LocalKey<T>>::with
  22: futures::future::Future::wait
  23: <jsonrpc_core::io::IoHandler<M>>::handle_request_sync
  24: migration_core::rpc_api::RpcApi::handle
  25: migration_engine::main
  26: std::rt::lang_start::{{closure}}
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
  29: std::rt::lang_start_internal
  30: main

    at ChildProcess.<anonymous> (/Users/nikolasburk/.config/yarn/global/node_modules/prisma2/build/index.js:82645:28)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
```

**Comment by nikolasburk** [comment]
Fixed it by adjusting the datamodel as follows:

```
model User {
  id: Int @id
  createdAt: DateTime @default(now())
  email: String @unique
  name: String
  role: Role @default(value: USER)
  posts: Post[]
  profile: Profile @relation(link: INLINE)
}

model Profile {
  id: Int @id
  user: User
  bio: String
}

model Post {
  id: Int @id
  createdAt: DateTime @default(now())
  updatedAt: DateTime @updatedAt
  author: User
  published: Boolean @default(value: false)
  categories: Category[] @relation(name: "PostToCategory")
}

model Category {
  id: Int @id
  name: String
  posts: Post[] @relation(name: "PostToCategory")
}

enum Role {
  USER
  ADMIN
}
```
