### ISSUE TITLE
createdAt with default doesn't work

### ISSUE THREAD

**Issue by divyenduz** [prisma/next#34]
Datamodel

```
model Post {
  id Int @id
  createdAt DateTime  @default(now())
  updatedAt DateTime @updatedAt
  published Boolean @default(false)
  title String
  content String?
  author User
}
```

Photon (doesn't allow adding `createdAt` manually)

```
const result = await photon.posts.create({
    data: {
      title: title,
      content: content,
      author: { connect: { email: authorEmail } }
    }
  });
```

Query sent to query engine
```
  photon mutation {
  photon   createPost(data: {
  photon     title: "Title 1"
  photon     content: "Content 1"
  photon     author: {
  photon       connect: {
  photon         email: "alice@prisma.io"
  photon       }
  photon     }                                                                                                                                                             photon   }) {
  photon     id                                                                                                                                                            photon     createdAt
  photon     updatedAt
  photon     published
  photon     title
  photon     content
  photon   }
  photon } +0ms
```

**Comment by divyenduz** [comment]
Error

```
(node:30720) UnhandledPromiseRejectionWarning: Error: [
  {
    "error": "ConnectorError(NullConstraintViolation { field_name: \"Post.createdAt\" })"
  }
]
    at NodeEngine.handleErrors (/Users/divyendusingh/Documents/prisma/prisma-faker-example/node_modules/@generated/photon/runtime/index.js:1356:15)
    at response.json.then.result (/Users/divyendusingh/Documents/prisma/prisma-faker-example/node_modules/@generated/photon/runtime/index.js:1331:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:30720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
