### ISSUE TITLE
Race condition in `prisma dev`

### ISSUE THREAD

**Issue by mavilein** [prisma/next#44]
I ran `prisma dev` and the photon generation seemed to take a bit longer and then the other generator failed because the files were not there yet:
```
🏋️‍  Watching for changes in datamodel.prisma

Changes since last prisma lift create



Running Photon JS Client
Done in 1.63s
Running Photogen
{ Error: Cannot find module '@generated/photon'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.2286 (/usr/local/lib/node_modules/prisma2/build/index.js:75138:18)
    at __webpack_require__ (/usr/local/lib/node_modules/prisma2/build/index.js:23:30)
    at getPhotogenRuntime (/usr/local/lib/node_modules/prisma2/build/index.js:130277:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/prisma2/build/index.js:130287:39)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/prisma2/build/index.js:130258:71 code: 'MODULE_NOT_FOUND' }
```

**Comment by mavilein** [comment]
Update: this happens even on the second run although the files are present in the file system.

**Comment by timsuchanek** [comment]
Should be fixed by  now, plz confirm @mavilein
