### ISSUE TITLE
Setting a scalar list in nested create triggers using `set`: "Error: Oops. This must not happen"

### ISSUE THREAD

**Issue by nikolasburk** [prisma/next#46]
Datamodel:

```
datasource db {
  provider = "sqlite"
  url      = "file:db/next.db"
  default  = true
}

generator photon {
  provider = "javascript"
  output = "node_modules/@generated/photon"
}

model User {
  id Int @id
  name String?
  posts Post[]
}         

model Post {
  id Int @id
  title String
  tags String[]
  author User
}
```

Code:

```js
const newUser = await photon.users.create({
  data: {
    name: "Mark",
    posts: {
      create: {
        title: "Hello World",
        tags: {
          set: ["asd"]
        }
      }
    }
  },
})
console.log(newUser)
```

Error:

```
$ ts-node main.ts
Error: Oops. This must not happen
    at valueToArg (/Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3256:11)
    at /Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3303:21
    at Array.reduce (<anonymous>)
    at objectToArgs (/Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3283:30)
    at /Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3164:32
    at Array.map (<anonymous>)
    at valueToArg (/Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3137:36)
    at /Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3303:21
    at Array.reduce (<anonymous>)
    at objectToArgs (/Users/nikolasburk/Desktop/prisma2-testing-session/next/node_modules/@generated/photon/runtime/index.js:3283:30)
✨  Done in 1.11s.
```

**Comment by divyenduz** [comment]
This also happens in 

```
await photon.posts.deleteMany({
  where: {
     id: {
      in: [1, 2]
     }
    }
}); // Error: Oops. This must not happen
```

**Comment by timsuchanek** [comment]
Fixed
