### ISSUE TITLE
migration-engine and prisma don't work inside lambda

### ISSUE THREAD

**Issue by matthewmueller** [prisma/next#73]
@prisma/backend 

**Steps to Reproduce:**

```sh
mkdir lambda && cd lambda
curl -o migration-engine-glibc https://s3-eu-west-1.amazonaws.com/prisma-native/alpha/latest/linux-glibc/migration-engine
curl -o migration-engine-musl https://s3-eu-west-1.amazonaws.com/prisma-native/alpha/latest/linux-musl/migration-engine
curl -o prisma-glibc https://s3-eu-west-1.amazonaws.com/prisma-native/alpha/latest/linux-glibc/prisma
curl -o prisma-musl https://s3-eu-west-1.amazonaws.com/prisma-native/alpha/latest/linux-musl/prisma
# todo: also fix permission plz :-)
chmod +x migration-engine-glibc migration-engine-musl prisma-glibc prisma-musl
```

In `lambda/`, Create an **index.js**:

```js
const os = require('os')
const { execSync } = require('child_process')

exports.handler = function(event, ctx, fn) {
  console.log(execSync('./prisma-musl').toString())
  fn(null)
}
```

Now inside `lambda/` run:

```
docker run --rm -v "$PWD":/var/task lambci/lambda:nodejs8.10 index.handler
```

You'll see:

```
START RequestId: 86ae9067-25bd-1b5b-3b09-3f6d917b42c3 Version: $LATEST
/bin/sh: ./prisma-musl: /lib/ld64.so.1: bad ELF interpreter: No such file or directory
2019-06-16T09:55:35.784Z	86ae9067-25bd-1b5b-3b09-3f6d917b42c3	Error: Command failed: ./prisma-musl
/bin/sh: ./prisma-musl: /lib/ld64.so.1: bad ELF interpreter: No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at exports.handler (/var/task/index.js:5:15)
```

You can then modify the index.js and see it with other binaries.

If you run `prisma-glibc`, you'll see:

```
START RequestId: 328fbca9-8987-1c19-497d-ba31e148cb8f Version: $LATEST
./prisma-glibc: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
2019-06-16T11:16:44.258Z	328fbca9-8987-1c19-497d-ba31e148cb8f	Error: Command failed: ./prisma-glibc
./prisma-glibc: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at exports.handler (/var/task/index.js:5:15)
``` 

Though I'd imagine this would be expected.

**Comment by matthewmueller** [comment]
Depends
