### ISSUE TITLE
Photon: `startsWith` and `endsWith` stringFilter throws

### ISSUE THREAD

**Issue by peterp** [prisma/next#92]
`equals` and `contains` work

```terminal
prisma2 -v
prisma2@0.0.68
```

```
{
  "errors": [
    {
      "message": "{\n  \"message\": \"request to http://localhost:57383/ failed, reason: socket hang up\",\n  \"type\": \"system\",\n  \"errno\": \"ECONNRESET\",\n  \"code\": \"ECONNRESET\"\n}",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "documents"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "query": "query {\n  findManyDocument(where: {\n    path_startsWith: \"://\"\n  }) {\n    id\n    name\n    path\n    content\n  }\n}",
          "error": {
            "message": "request to http://localhost:57383/ failed, reason: socket hang up",
            "type": "system",
            "errno": "ECONNRESET",
            "code": "ECONNRESET"
          },
          "logs": "thread 'arbiter:b5fbe545-33e3-4f03-aa17-b67f340bd73e:actix-net-worker-1thread 'arbiter:c5335df2-6758-4ed6-88ba-49d5caadb834:actix-net-worker-2' panicked at 'called `Result::unwrap()` on an `Err` value: FieldNotFound { name: \"path_startsWith\", model: \"Document\" }', src/libcore/result.rs' panicked at 'called `Result::unwrap()` on an `Err` value: FieldNotFound { name: \"path_startsWith\", model: \"Document\" }:', 997src/libcore/result.rs:997::55\n\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\nstack backtrace:\n   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace\n   1: std::sys_common::backtrace::_print\n   2: std::panicking::default_hook::{{closure}}\n   3: std::panicking::default_hook\n   4: std::panicking::rust_panic_with_hook\n   5: std::panicking::continue_panic_fmt\n   6: rust_begin_unwind\n   7: core::panicking::panic_fmt\n   8: core::result::unwrap_failed\n   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once\n  10: <&mut I as core::iter::traits::iterator::Iterator>::next\n  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter\n  12: core::builders::filters::extract_filter\n  13: core::builders::utils::extract_filter\n  14: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::fold\n  15: <core::builders::many::ManyBuilder<'f> as core::builders::BuilderExt>::build\n  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once\n  17: <&mut I as core::iter::traits::iterator::Iterator>::next\n  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter\n  19: core::builders::root::RootBuilder::build_query\n  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once\n  21: <&mut I as core::iter::traits::iterator::Iterator>::next\n  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter\n  23: core::builders::root::RootBuilder::build\n  24: <prisma::req_handlers::graphql::GraphQlRequestHandler as prisma::req_handlers::RequestHandler>::handle\n  25: prisma::http_handler\n  26: <F as actix_web::with::FnWith<T, R>>::call_with\n  27: <actix_web::with::WithHandlerFut<T, S, R> as futures::future::Future>::poll\n  28: <actix_web::pipeline::PipelineState<S, H>>::poll\n  29: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::handler::HttpHandlerTask>::poll_io\n  30: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll_handler\n  31: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll\n  32: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll\n  33: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll\n  34: <actix_net::service::and_then::AndThenFuture<A, B> as futures::future::Future>::poll\n  35: <futures::future::chain::Chain<A, B, C>>::poll\n  36: futures::task_impl::std::set\n  37: <futures::task_impl::Spawn<T>>::poll_future_notify\n  38: tokio_current_thread::CurrentRunner::set_spawn\n  39: <tokio_current_thread::scheduler::Scheduler<U>>::tick\n  40: <tokio_current_thread::Entered<'a, P>>::block_on\n  41: <std::thread::local::LocalKey<T>>::with\n  42: <std::thread::local::LocalKey<T>>::with\n  43: <std::thread::local::LocalKey<T>>::with\n  44: <std::thread::local::LocalKey<T>>::with\n  45: tokio::runtime::current_thread::runtime::Runtime::block_on\nnote: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.\nstack backtrace:\n   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace\n   1: std::sys_common::backtrace::_print\n   2: std::panicking::default_hook::{{closure}}\n   3: std::panicking::default_hook\n   4: std::panicking::rust_panic_with_hook\n   5: std::panicking::continue_panic_fmt\n   6: rust_begin_unwind\n   7: core::panicking::panic_fmt\n   8: core::result::unwrap_failed\n   9: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once\n  10: <&mut I as core::iter::traits::iterator::Iterator>::next\n  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter\n  12: core::builders::filters::extract_filter\n  13: core::builders::utils::extract_filter\n  14: <core::iter::adapters::Map<I, F> as core::iter::traits::iterator::Iterator>::fold\n  15: <core::builders::many::ManyBuilder<'f> as core::builders::BuilderExt>::build\n  16: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once\n  17: <&mut I as core::iter::traits::iterator::Iterator>::next\n  18: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter\n  19: core::builders::root::RootBuilder::build_query\n  20: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once\n  21: <&mut I as core::iter::traits::iterator::Iterator>::next\n  22: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T, I>>::from_iter\n  23: core::builders::root::RootBuilder::build\n  24: <prisma::req_handlers::graphql::GraphQlRequestHandler as prisma::req_handlers::RequestHandler>::handle\n  25: prisma::http_handler\n  26: <F as actix_web::with::FnWith<T, R>>::call_with\n  27: <actix_web::with::WithHandlerFut<T, S, R> as futures::future::Future>::poll\n  28: <actix_web::pipeline::PipelineState<S, H>>::poll\n  29: <actix_web::pipeline::Pipeline<S, H> as actix_web::server::handler::HttpHandlerTask>::poll_io\n  30: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll_handler\n  31: <actix_web::server::h1::Http1Dispatcher<T, H>>::poll\n  32: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll\n  33: <actix_web::server::channel::HttpChannel<T, H> as futures::future::Future>::poll\n  34: <actix_net::service::and_then::AndThenFuture<A, B> as futures::future::Future>::poll\n  35: <futures::future::chain::Chain<A, B, C>>::poll\n  36: futures::task_impl::std::set\n  37: <futures::task_impl::Spawn<T>>::poll_future_notify\n  38: tokio_current_thread::CurrentRunner::set_spawn\n  39: <tokio_current_thread::scheduler::Scheduler<U>>::tick\n  40: <tokio_current_thread::Entered<'a, P>>::block_on\n  41: <std::thread::local::LocalKey<T>>::with\n  42: <std::thread::local::LocalKey<T>>::with\n  43: <std::thread::local::LocalKey<T>>::with\n  44: <std::thread::local::LocalKey<T>>::with\n  45: tokio::runtime::current_thread::runtime::Runtime::block_on\n",
          "isPanicked": false,
          "stacktrace": [
            "Error: {",
            "  \"message\": \"request to http://localhost:57383/ failed, reason: socket hang up\",",
            "  \"type\": \"system\",",
            "  \"errno\": \"ECONNRESET\",",
            "  \"code\": \"ECONNRESET\"",
            "}",
            "    at NodeEngine.handleErrors (/Users/peterp/Personal/der-spielplatz/api/generated/photon/runtime/index.js:1550:15)",
            "    at currentRequestPromise.cross_fetch_1.default.then.catch.errors (/Users/peterp/Personal/der-spielplatz/api/generated/photon/runtime/index.js:1527:25)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by peterp** [comment]
My apologies, this has nothing to do with the demo. I'll create a respective ticket in the correct repo.
